### ISSUE TITLE
Messages cannot be sent out late at night

### ISSUE THREAD

**Issue by ccostino** [18F/dolores-landingham-slack-bot#111]
It appears there is another issue related to the employee message matching when sending messages late at night, this time in checking the start date of the employee.  After a certain point in time in the evening (I was testing between 9:00 PM and 10:00 PM) two tests start to fail:

* MessageEmployeeMatcher#run matches messages to users based on days after start
* MessageEmployeeMatcher#run ignores messages that have already been sent to users

And messages will not be sent when testing things manually.

I suspect this is a similar issue that @jessieay and I had fixed with the time matching where we also had to check that the user's local time was still during the same day as the UTC time the app uses internally.  Checking to see which day to send a message out may require a similar guard clause in it.

**Comment by jessieay** [comment]
ha! that's really interesting. To be clear: you were testing between 9pm and 10pm ET?

**Comment by ccostino** [comment]
I know, this just doesn't seem to end!  Yes, I was testing between 9 PM and 10 PM EST. :-)

**Comment by melodykramer** [comment]
I think this has been fixed - all of the messages are now being sent at normal times. May I close this issue?

**Comment by jessieay** [comment]
we still cannot send messages past 4pm because of a timezone issue and how that works for users in PST.  I think we can keep this open and try to fix this

**Comment by melodykramer** [comment]
Oh, I see - ok!

**Comment by jessieay** [comment]
This is a real doozy. Time zones arghhh!!

Right now, the reason we cannot send out message past 4pm is that we ensure that the employee's day is the same as the day in GMT (https://github.com/18F/dolores-landingham-bot/blob/master/app/services/message_employee_matcher.rb#L29)

Since 18F has people on the West Coast, if we schedule a message to go out at 5pm, it will never get sent because 5pm PT is past midnight in GMT.

What we need to do to fix this is figure out a way to send messages to users past 5pm without re-introducing the bug that was fixed here: https://github.com/18F/dolores-landingham-bot/commit/625bacae5f4f9a722b2b7eb45f80237a857a36fb#diff-7592c8fee0982ee338764fde2f50dd9a

**Comment by dijonkitchen** [comment]
Is this still relevant now that Slack has Do Not Disturb built in? 

https://get.slack.help/hc/en-us/articles/214908388-Using-Do-Not-Disturb-in-Slack

**Comment by jessieay** [comment]
Hi! Yes this is relevant because it is related to anything after 4pm PT. So if we wanted to send something at 4:30pm PT we couldn't. Or we could, but right now the code does not allow it.
